export const errorCodes = {
  ALIAS_UNAVAILABLE: "ALIAS_UNAVAILABLE",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  CACHE_UNAVAILABLE: "CACHE_UNAVAILABLE",
  DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
  DEPENDENCY_UNAVAILABLE: "DEPENDENCY_UNAVAILABLE",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_EXPIRY: "INVALID_EXPIRY",
  LINK_EXPIRED: "LINK_EXPIRED",
  LINK_NOT_FOUND: "LINK_NOT_FOUND",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  TOKEN_REUSE_DETECTED: "TOKEN_REUSE_DETECTED",
  UNSAFE_DESTINATION: "UNSAFE_DESTINATION",
  VALIDATION_FAILED: "VALIDATION_FAILED"
} as const;

export type ErrorCode = (typeof errorCodes)[keyof typeof errorCodes];
